name: CI

on:
  push:
    branches: ["**"]
  pull_request:
  workflow_dispatch:

jobs:
  smoke:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'

      - name: Install system dependencies (Java for PySpark)
        run: sudo apt-get update && sudo apt-get install -y default-jre-headless

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements_streamlit_cloud.txt

      - name: Smoke import test (no Spark session start)
        env:
          SPARK_LOCAL_IP: 127.0.0.1
        run: |
          python - <<'PY'
          import importlib
          modules = [
              'streamlit',
              'pandas',
              'pyarrow',
              'requests',
              'pyspark',
          ]
          for m in modules:
              importlib.import_module(m)
          print('Imported OK:', ', '.join(modules))
          PY

